In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer

In [7]:
pd.set_option('display.max_columns', None)

In [9]:
df=pd.read_csv("dataset/train.csv")

In [11]:
df.head()

,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,loan_status,next_payment_date,member_id,purpose,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,issue_date_year,issue_date_month,issue_date_day,issue_date_weekday,issue_date_hour
0,CA,INDIVIDUAL,4 years,"Windsor Solutions, Inc.",D,RENT,2021-08-07,2021-07-15,2021-07-12,Current,2021-07-13,1.251026e+06,Debt consolidation,36 months,Source Verified,82438.124601,0.072151,62.006774,0.161206,9586.945180,1.953600,NaN,2021,8,7,5,0
1,PA,INDIVIDUAL,3 years,Grant & Eisenhofer,C,MORTGAGE,2021-04-09,2021-05-16,2021-03-13,Charged Off,2022-01-13,2.947135e+05,wedding,36 months,Not Verified,52347.892639,0.140367,373.547998,0.117188,2213.200815,22.458280,12901.399781,2021,4,9,4,0
2,DC,INDIVIDUAL,6 years,VALLEY PLUMBING COMPANY,B,RENT,2021-07-10,2021-05-16,2021-03-12,Fully Paid,2021-08-14,6.013015e+05,Debt consolidation,36 months,Verified,-38314.485684,0.125850,529.631006,0.089163,15608.890161,NaN,10082.118704,2021,7,10,5,0
3,WI,INDIVIDUAL,7 years,Housing Investments Inc,G,MORTGAGE,2021-10-11,2021-04-16,2021-07-14,Fully Paid,2021-05-15,1.027941e+06,Debt consolidation,60 months,Verified,254889.785659,0.148349,1057.386266,0.171302,16700.391717,2.814647,NaN,2021,10,11,0,0
4,NY,INDIVIDUAL,10+ years,Massage Envy,C,MORTGAGE,2021-01-10,2021-10-12,2021-01-14,Charged Off,2021-02-15,1.087496e+06,credit card,60 months,Verified,NaN,NaN,510.555677,0.091857,4109.600739,NaN,13485.994361,2021,1,10,6,0

In [13]:
df.shape

(75001, 27)

In [15]:
df.columns

Index(['address_state', 'application_type', 'emp_length', 'emp_title', 'grade',
       'home_ownership', 'issue_date', 'last_credit_pull_date',
       'last_payment_date', 'loan_status', 'next_payment_date', 'member_id',
       'purpose', 'term', 'verification_status', 'annual_income', 'dti',
       'installment', 'int_rate', 'loan_amount', 'total_acc', 'total_payment',
       'issue_date_year', 'issue_date_month', 'issue_date_day',
       'issue_date_weekday', 'issue_date_hour'],
      dtype='object')

## 1. Data Cleaning

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75001 entries, 0 to 75000
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   address_state          75001 non-null  object
 1   application_type       75001 non-null  object
 2   emp_length             75001 non-null  object
 3   emp_title              75001 non-null  object
 4   grade                  75001 non-null  object
 5   home_ownership         75001 non-null  object
 6   issue_date             75001 non-null  object
 7   last_credit_pull_date  75001 non-null  object
 8   last_payment_date      75001 non-null  object
 9   loan_status            75001 non-null  object
 10  next_payment_date      75001 non-null  object
 11  member_id              75001 non-null  float64
 12  purpose                75001 non-null  object
 13  term                   75001 non-null  object
 14  verification_status    75001 non-null  object
 15  annual_income          67501 non-null  float64
 16  dti                    63751 non-null  float64
 17  installment            71251 non-null  float64
 18  int_rate               60001 non-null  float64
 19  loan_amount            67501 non-null  float64
 20  total_acc              67501 non-null  float64
 21  total_payment          56251 non-null  float64
 22  issue_date_year        75001 non-null  int64
 23  issue_date_month       75001 non-null  int64
 24  issue_date_day         75001 non-null  int64
 25  issue_date_weekday     75001 non-null  int64
 26  issue_date_hour        75001 non-null  int64
dtypes: float64(8), int64(5), object(14)
memory usage: 15.4+ MB

In [20]:
df.isnull().sum()/len(df)*100

address_state             0.000000
application_type          0.000000
emp_length                0.000000
emp_title                 0.000000
grade                     0.000000
home_ownership            0.000000
issue_date                0.000000
last_credit_pull_date     0.000000
last_payment_date         0.000000
loan_status               0.000000
next_payment_date         0.000000
member_id                 0.000000
purpose                   0.000000
term                      0.000000
verification_status       0.000000
annual_income             9.999867
dti                      14.999800
installment               4.999933
int_rate                 19.999733
loan_amount               9.999867
total_acc                 9.999867
total_payment            24.999667
issue_date_year           0.000000
issue_date_month          0.000000
issue_date_day            0.000000
issue_date_weekday        0.000000
issue_date_hour           0.000000
dtype: float64

In [22]:
df['last_credit_pull_date'] = pd.to_datetime(df['last_credit_pull_date'])
df['last_payment_date'] = pd.to_datetime(df['last_payment_date'])
df['next_payment_date'] = pd.to_datetime(df['next_payment_date'])

In [24]:
df['last_credit_pull_date_year'] = df['last_credit_pull_date'].dt.year
df['last_credit_pull_date_month'] = df['last_credit_pull_date'].dt.month
df['last_credit_pull_date_day'] = df['last_credit_pull_date'].dt.day
df['last_credit_pull_date_weekday'] = df['last_credit_pull_date'].dt.dayofweek

In [26]:
df['last_payment_date_year'] = df['last_payment_date'].dt.year
df['last_payment_date_month'] = df['last_payment_date'].dt.month
df['last_payment_date_day'] = df['last_payment_date'].dt.day
df['last_payment_date_weekday'] = df['last_payment_date'].dt.dayofweek

In [28]:
df['next_payment_date_year'] = df['next_payment_date'].dt.year
df['next_payment_date_month'] = df['next_payment_date'].dt.month
df['next_payment_date_day'] = df['next_payment_date'].dt.day
df['next_payment_date_weekday'] = df['next_payment_date'].dt.dayofweek

In [30]:
df.head()

,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,loan_status,next_payment_date,member_id,purpose,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,issue_date_year,issue_date_month,issue_date_day,issue_date_weekday,issue_date_hour,last_credit_pull_date_year,last_credit_pull_date_month,last_credit_pull_date_day,last_credit_pull_date_weekday,last_payment_date_year,last_payment_date_month,last_payment_date_day,last_payment_date_weekday,next_payment_date_year,next_payment_date_month,next_payment_date_day,next_payment_date_weekday
0,CA,INDIVIDUAL,4 years,"Windsor Solutions, Inc.",D,RENT,2021-08-07,2021-07-15,2021-07-12,Current,2021-07-13,1.251026e+06,Debt consolidation,36 months,Source Verified,82438.124601,0.072151,62.006774,0.161206,9586.945180,1.953600,NaN,2021,8,7,5,0,2021,7,15,3,2021,7,12,0,2021,7,13,1
1,PA,INDIVIDUAL,3 years,Grant & Eisenhofer,C,MORTGAGE,2021-04-09,2021-05-16,2021-03-13,Charged Off,2022-01-13,2.947135e+05,wedding,36 months,Not Verified,52347.892639,0.140367,373.547998,0.117188,2213.200815,22.458280,12901.399781,2021,4,9,4,0,2021,5,16,6,2021,3,13,5,2022,1,13,3
2,DC,INDIVIDUAL,6 years,VALLEY PLUMBING COMPANY,B,RENT,2021-07-10,2021-05-16,2021-03-12,Fully Paid,2021-08-14,6.013015e+05,Debt consolidation,36 months,Verified,-38314.485684,0.125850,529.631006,0.089163,15608.890161,NaN,10082.118704,2021,7,10,5,0,2021,5,16,6,2021,3,12,4,2021,8,14,5
3,WI,INDIVIDUAL,7 years,Housing Investments Inc,G,MORTGAGE,2021-10-11,2021-04-16,2021-07-14,Fully Paid,2021-05-15,1.027941e+06,Debt consolidation,60 months,Verified,254889.785659,0.148349,1057.386266,0.171302,16700.391717,2.814647,NaN,2021,10,11,0,0,2021,4,16,4,2021,7,14,2,2021,5,15,5
4,NY,INDIVIDUAL,10+ years,Massage Envy,C,MORTGAGE,2021-01-10,2021-10-12,2021-01-14,Charged Off,2021-02-15,1.087496e+06,credit card,60 months,Verified,NaN,NaN,510.555677,0.091857,4109.600739,NaN,13485.994361,2021,1,10,6,0,2021,10,12,1,2021,1,14,3,2021,2,15,0

In [32]:
df.shape

(75001, 39)

In [34]:
df.drop(columns=["issue_date","last_credit_pull_date","last_payment_date","next_payment_date"],inplace=True)

In [36]:
df.shape

(75001, 35)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75001 entries, 0 to 75000
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   address_state                  75001 non-null  object
 1   application_type               75001 non-null  object
 2   emp_length                     75001 non-null  object
 3   emp_title                      75001 non-null  object
 4   grade                          75001 non-null  object
 5   home_ownership                 75001 non-null  object
 6   loan_status                    75001 non-null  object
 7   member_id                      75001 non-null  float64
 8   purpose                        75001 non-null  object
 9   term                           75001 non-null  object
 10  verification_status            75001 non-null  object
 11  annual_income                  67501 non-null  float64
 12  dti                            63751 non-null  float64
 13  installment                    71251 non-null  float64
 14  int_rate                       60001 non-null  float64
 15  loan_amount                    67501 non-null  float64
 16  total_acc                      67501 non-null  float64
 17  total_payment                  56251 non-null  float64
 18  issue_date_year                75001 non-null  int64
 19  issue_date_month               75001 non-null  int64
 20  issue_date_day                 75001 non-null  int64
 21  issue_date_weekday             75001 non-null  int64
 22  issue_date_hour                75001 non-null  int64
 23  last_credit_pull_date_year     75001 non-null  int32
 24  last_credit_pull_date_month    75001 non-null  int32
 25  last_credit_pull_date_day      75001 non-null  int32
 26  last_credit_pull_date_weekday  75001 non-null  int32
 27  last_payment_date_year         75001 non-null  int32
 28  last_payment_date_month        75001 non-null  int32
 29  last_payment_date_day          75001 non-null  int32
 30  last_payment_date_weekday      75001 non-null  int32
 31  next_payment_date_year         75001 non-null  int32
 32  next_payment_date_month        75001 non-null  int32
 33  next_payment_date_day          75001 non-null  int32
 34  next_payment_date_weekday      75001 non-null  int32
dtypes: float64(8), int32(12), int64(5), object(10)
memory usage: 16.6+ MB

In [40]:
df.head()

,address_state,application_type,emp_length,emp_title,grade,home_ownership,loan_status,member_id,purpose,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,issue_date_year,issue_date_month,issue_date_day,issue_date_weekday,issue_date_hour,last_credit_pull_date_year,last_credit_pull_date_month,last_credit_pull_date_day,last_credit_pull_date_weekday,last_payment_date_year,last_payment_date_month,last_payment_date_day,last_payment_date_weekday,next_payment_date_year,next_payment_date_month,next_payment_date_day,next_payment_date_weekday
0,CA,INDIVIDUAL,4 years,"Windsor Solutions, Inc.",D,RENT,Current,1.251026e+06,Debt consolidation,36 months,Source Verified,82438.124601,0.072151,62.006774,0.161206,9586.945180,1.953600,NaN,2021,8,7,5,0,2021,7,15,3,2021,7,12,0,2021,7,13,1
1,PA,INDIVIDUAL,3 years,Grant & Eisenhofer,C,MORTGAGE,Charged Off,2.947135e+05,wedding,36 months,Not Verified,52347.892639,0.140367,373.547998,0.117188,2213.200815,22.458280,12901.399781,2021,4,9,4,0,2021,5,16,6,2021,3,13,5,2022,1,13,3
2,DC,INDIVIDUAL,6 years,VALLEY PLUMBING COMPANY,B,RENT,Fully Paid,6.013015e+05,Debt consolidation,36 months,Verified,-38314.485684,0.125850,529.631006,0.089163,15608.890161,NaN,10082.118704,2021,7,10,5,0,2021,5,16,6,2021,3,12,4,2021,8,14,5
3,WI,INDIVIDUAL,7 years,Housing Investments Inc,G,MORTGAGE,Fully Paid,1.027941e+06,Debt consolidation,60 months,Verified,254889.785659,0.148349,1057.386266,0.171302,16700.391717,2.814647,NaN,2021,10,11,0,0,2021,4,16,4,2021,7,14,2,2021,5,15,5
4,NY,INDIVIDUAL,10+ years,Massage Envy,C,MORTGAGE,Charged Off,1.087496e+06,credit card,60 months,Verified,NaN,NaN,510.555677,0.091857,4109.600739,NaN,13485.994361,2021,1,10,6,0,2021,10,12,1,2021,1,14,3,2021,2,15,0

In [42]:
len(df.address_state.unique())

50

In [44]:
len(df.application_type.unique())

1

In [46]:
## Dropping application_type since it has only one unique value
df.drop(columns=["application_type"], inplace=True)

In [48]:
(df.emp_length.unique())

array(['4 years', '3 years', '6 years', '7 years', '10+ years',
       '< 1 year', '5 years', '8 years', '2 years', '1 year', '9 years'],
      dtype=object)

In [50]:
## Function to convert emp_length into numerical:
def convert_emp_length(len):
    if len=="10+ years":
        return 10
    elif len=="< 1 year":
        return 0.5
    else:
        return int(len.split()[0])

In [52]:
df["emp_length"]=df["emp_length"].apply(convert_emp_length)

In [54]:
df.head()

,address_state,emp_length,emp_title,grade,home_ownership,loan_status,member_id,purpose,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,issue_date_year,issue_date_month,issue_date_day,issue_date_weekday,issue_date_hour,last_credit_pull_date_year,last_credit_pull_date_month,last_credit_pull_date_day,last_credit_pull_date_weekday,last_payment_date_year,last_payment_date_month,last_payment_date_day,last_payment_date_weekday,next_payment_date_year,next_payment_date_month,next_payment_date_day,next_payment_date_weekday
0,CA,4.0,"Windsor Solutions, Inc.",D,RENT,Current,1.251026e+06,Debt consolidation,36 months,Source Verified,82438.124601,0.072151,62.006774,0.161206,9586.945180,1.953600,NaN,2021,8,7,5,0,2021,7,15,3,2021,7,12,0,2021,7,13,1
1,PA,3.0,Grant & Eisenhofer,C,MORTGAGE,Charged Off,2.947135e+05,wedding,36 months,Not Verified,52347.892639,0.140367,373.547998,0.117188,2213.200815,22.458280,12901.399781,2021,4,9,4,0,2021,5,16,6,2021,3,13,5,2022,1,13,3
2,DC,6.0,VALLEY PLUMBING COMPANY,B,RENT,Fully Paid,6.013015e+05,Debt consolidation,36 months,Verified,-38314.485684,0.125850,529.631006,0.089163,15608.890161,NaN,10082.118704,2021,7,10,5,0,2021,5,16,6,2021,3,12,4,2021,8,14,5
3,WI,7.0,Housing Investments Inc,G,MORTGAGE,Fully Paid,1.027941e+06,Debt consolidation,60 months,Verified,254889.785659,0.148349,1057.386266,0.171302,16700.391717,2.814647,NaN,2021,10,11,0,0,2021,4,16,4,2021,7,14,2,2021,5,15,5
4,NY,10.0,Massage Envy,C,MORTGAGE,Charged Off,1.087496e+06,credit card,60 months,Verified,NaN,NaN,510.555677,0.091857,4109.600739,NaN,13485.994361,2021,1,10,6,0,2021,10,12,1,2021,1,14,3,2021,2,15,0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75001 entries, 0 to 75000
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   address_state                  75001 non-null  object
 1   emp_length                     75001 non-null  float64
 2   emp_title                      75001 non-null  object
 3   grade                          75001 non-null  object
 4   home_ownership                 75001 non-null  object
 5   loan_status                    75001 non-null  object
 6   member_id                      75001 non-null  float64
 7   purpose                        75001 non-null  object
 8   term                           75001 non-null  object
 9   verification_status            75001 non-null  object
 10  annual_income                  67501 non-null  float64
 11  dti                            63751 non-null  float64
 12  installment                    71251 non-null  float64
 13  int_rate                       60001 non-null  float64
 14  loan_amount                    67501 non-null  float64
 15  total_acc                      67501 non-null  float64
 16  total_payment                  56251 non-null  float64
 17  issue_date_year                75001 non-null  int64
 18  issue_date_month               75001 non-null  int64
 19  issue_date_day                 75001 non-null  int64
 20  issue_date_weekday             75001 non-null  int64
 21  issue_date_hour                75001 non-null  int64
 22  last_credit_pull_date_year     75001 non-null  int32
 23  last_credit_pull_date_month    75001 non-null  int32
 24  last_credit_pull_date_day      75001 non-null  int32
 25  last_credit_pull_date_weekday  75001 non-null  int32
 26  last_payment_date_year         75001 non-null  int32
 27  last_payment_date_month        75001 non-null  int32
 28  last_payment_date_day          75001 non-null  int32
 29  last_payment_date_weekday      75001 non-null  int32
 30  next_payment_date_year         75001 non-null  int32
 31  next_payment_date_month        75001 non-null  int32
 32  next_payment_date_day          75001 non-null  int32
 33  next_payment_date_weekday      75001 non-null  int32
dtypes: float64(9), int32(12), int64(5), object(8)
memory usage: 16.0+ MB

In [58]:
df.home_ownership.unique()

array(['RENT', 'MORTGAGE', 'OWN', 'OTHER', 'NONE'], dtype=object)

In [60]:
df.loan_status.unique()

array(['Current', 'Charged Off', 'Fully Paid'], dtype=object)

In [62]:
df.purpose.unique()

array(['Debt consolidation', 'wedding', 'credit card', 'small business',
       'car', 'other', 'major purchase', 'moving', 'home improvement',
       'vacation', 'medical', 'educational', 'house', 'renewable_energy'],
      dtype=object)

In [64]:
df.term.unique()

array([' 36 months', ' 60 months'], dtype=object)

In [66]:
df["term"]=df["term"].apply(lambda x:int(x.split()[0]))

In [68]:
df.term.unique()

array([36, 60], dtype=int64)

In [70]:
df.verification_status.unique()

array(['Source Verified', 'Not Verified', 'Verified'], dtype=object)

In [72]:
len(df.emp_title.unique())

21328

In [74]:
emp_title_counts=df.emp_title.value_counts()

In [76]:
df['emp_title_encoded'] = df['emp_title'].map(emp_title_counts)

In [78]:
df.drop(columns=["emp_title"],inplace=True)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75001 entries, 0 to 75000
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   address_state                  75001 non-null  object
 1   emp_length                     75001 non-null  float64
 2   grade                          75001 non-null  object
 3   home_ownership                 75001 non-null  object
 4   loan_status                    75001 non-null  object
 5   member_id                      75001 non-null  float64
 6   purpose                        75001 non-null  object
 7   term                           75001 non-null  int64
 8   verification_status            75001 non-null  object
 9   annual_income                  67501 non-null  float64
 10  dti                            63751 non-null  float64
 11  installment                    71251 non-null  float64
 12  int_rate                       60001 non-null  float64
 13  loan_amount                    67501 non-null  float64
 14  total_acc                      67501 non-null  float64
 15  total_payment                  56251 non-null  float64
 16  issue_date_year                75001 non-null  int64
 17  issue_date_month               75001 non-null  int64
 18  issue_date_day                 75001 non-null  int64
 19  issue_date_weekday             75001 non-null  int64
 20  issue_date_hour                75001 non-null  int64
 21  last_credit_pull_date_year     75001 non-null  int32
 22  last_credit_pull_date_month    75001 non-null  int32
 23  last_credit_pull_date_day      75001 non-null  int32
 24  last_credit_pull_date_weekday  75001 non-null  int32
 25  last_payment_date_year         75001 non-null  int32
 26  last_payment_date_month        75001 non-null  int32
 27  last_payment_date_day          75001 non-null  int32
 28  last_payment_date_weekday      75001 non-null  int32
 29  next_payment_date_year         75001 non-null  int32
 30  next_payment_date_month        75001 non-null  int32
 31  next_payment_date_day          75001 non-null  int32
 32  next_payment_date_weekday      75001 non-null  int32
 33  emp_title_encoded              75001 non-null  int64
dtypes: float64(9), int32(12), int64(7), object(6)
memory usage: 16.0+ MB

In [82]:
encoder = OneHotEncoder(drop='first', sparse=False)

In [84]:
encoded_df=encoder.fit_transform(df[["address_state", "home_ownership", "loan_status", "purpose", "verification_status"]])

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [86]:
encoded_df=pd.DataFrame(encoded_df, columns=encoder.get_feature_names_out(["address_state", "home_ownership", "loan_status", "purpose", "verification_status"]))

In [88]:
encoded_df.head()

,address_state_AL,address_state_AR,address_state_AZ,address_state_CA,address_state_CO,address_state_CT,address_state_DC,address_state_DE,address_state_FL,address_state_GA,address_state_HI,address_state_IA,address_state_ID,address_state_IL,address_state_IN,address_state_KS,address_state_KY,address_state_LA,address_state_MA,address_state_MD,address_state_ME,address_state_MI,address_state_MN,address_state_MO,address_state_MS,address_state_MT,address_state_NC,address_state_NE,address_state_NH,address_state_NJ,address_state_NM,address_state_NV,address_state_NY,address_state_OH,address_state_OK,address_state_OR,address_state_PA,address_state_RI,address_state_SC,address_state_SD,address_state_TN,address_state_TX,address_state_UT,address_state_VA,address_state_VT,address_state_WA,address_state_WI,address_state_WV,address_state_WY,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_status_Current,loan_status_Fully Paid,purpose_car,purpose_credit card,purpose_educational,purpose_home improvement,purpose_house,purpose_major purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small business,purpose_vacation,purpose_wedding,verification_status_Source Verified,verification_status_Verified
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [90]:
df1=df.drop(columns=["address_state", "home_ownership", "loan_status", "purpose", "verification_status"])

In [92]:
df2=pd.concat([df1,encoded_df],axis=1)

In [94]:
df2.head()

,emp_length,grade,member_id,term,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,issue_date_year,issue_date_month,issue_date_day,issue_date_weekday,issue_date_hour,last_credit_pull_date_year,last_credit_pull_date_month,last_credit_pull_date_day,last_credit_pull_date_weekday,last_payment_date_year,last_payment_date_month,last_payment_date_day,last_payment_date_weekday,next_payment_date_year,next_payment_date_month,next_payment_date_day,next_payment_date_weekday,emp_title_encoded,address_state_AL,address_state_AR,address_state_AZ,address_state_CA,address_state_CO,address_state_CT,address_state_DC,address_state_DE,address_state_FL,address_state_GA,address_state_HI,address_state_IA,address_state_ID,address_state_IL,address_state_IN,address_state_KS,address_state_KY,address_state_LA,address_state_MA,address_state_MD,address_state_ME,address_state_MI,address_state_MN,address_state_MO,address_state_MS,address_state_MT,address_state_NC,address_state_NE,address_state_NH,address_state_NJ,address_state_NM,address_state_NV,address_state_NY,address_state_OH,address_state_OK,address_state_OR,address_state_PA,address_state_RI,address_state_SC,address_state_SD,address_state_TN,address_state_TX,address_state_UT,address_state_VA,address_state_VT,address_state_WA,address_state_WI,address_state_WV,address_state_WY,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_status_Current,loan_status_Fully Paid,purpose_car,purpose_credit card,purpose_educational,purpose_home improvement,purpose_house,purpose_major purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small business,purpose_vacation,purpose_wedding,verification_status_Source Verified,verification_status_Verified
0,4.0,D,1.251026e+06,36,82438.124601,0.072151,62.006774,0.161206,9586.945180,1.953600,NaN,2021,8,7,5,0,2021,7,15,3,2021,7,12,0,2021,7,13,1,6,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,3.0,C,2.947135e+05,36,52347.892639,0.140367,373.547998,0.117188,2213.200815,22.458280,12901.399781,2021,4,9,4,0,2021,5,16,6,2021,3,13,5,2022,1,13,3,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,6.0,B,6.013015e+05,36,-38314.485684,0.125850,529.631006,0.089163,15608.890161,NaN,10082.118704,2021,7,10,5,0,2021,5,16,6,2021,3,12,4,2021,8,14,5,3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,7.0,G,1.027941e+06,60,254889.785659,0.148349,1057.386266,0.171302,16700.391717,2.814647,NaN,2021,10,11,0,0,2021,4,16,4,2021,7,14,2,2021,5,15,5,43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,10.0,C,1.087496e+06,60,NaN,NaN,510.555677,0.091857,4109.600739,NaN,13485.994361,2021,1,10,6,0,2021,10,12,1,2021,1,14,3,2021,2,15,0,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [96]:
df2.shape

(75001, 99)

In [98]:
label_encoder=LabelEncoder()
df2["grade"]=label_encoder.fit_transform(df2["grade"])

In [100]:
pd.DataFrame(label_encoder.inverse_transform(df2.grade))[0].unique()

array(['D', 'C', 'B', 'G', 'A', 'E', 'F'], dtype=object)

In [102]:
df2.to_csv('data.csv', index=False)

#### From here go to work2